name: Build Bootstrap

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Install dep
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libelf-dev llvm-dev
      - name: Run make
        run: |
          pushd examples/c
          make bootstrap
          chmod +x bootstrap
          popd
      - uses: actions/upload-artifact@v3
        with:
          name: executable
          path: |
            ./examples/c/bootstrap
